# Use an official Node runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /usr/src/

# Copy package.json and package-lock.json (or yarn.lock) into the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

# Build your app (if necessary)
RUN npm run build

# Inform Docker that the container listens on the specified network ports at runtime.
EXPOSE 3000

# Define the command to run your app
CMD [ "node", "dist/index.js" ]
